# Builder stage
ARG GOARCH
ARG GOARM
ARG BUILD_PLATFORM
ARG FINAL_IMAGE
FROM --platform=linux/${BUILD_PLATFORM} golang:1.17 AS builder
ENV GOPROXY=https://proxy.golang.org
ENV GO111MODULE=on
ENV CGO_ENABLED=1
ENV GOOS=linux

ARG GOARCH
ENV GOARCH=${GOARCH}
ARG FINAL_IMAGE
ENV FINAL_IMAGE=${FINAL_IMAGE}
ENV GOARM=${GOARM}
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y libsqlite3-dev build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory and add application code
WORKDIR /app
ADD . .

# Copy go mod and sum files and fetch dependencies
COPY go.mod go.sum ./
RUN go mod download

# Set environment for cgo
ENV CGO_ENABLED=1

# Build
RUN CGO_ENABLED=1 GOOS=linux go build -v -o haargos-output .

LABEL \
  io.hass.version="1.0.30" \
  io.hass.type="addon" \
  io.hass.arch="armhf|aarch64|i386|amd64"

# Final stage
FROM ${FINAL_IMAGE}
WORKDIR /root/
COPY --from=builder /app/haargos-output ./haargos
CMD ["./haargos"]
