# Builder stage
ARG GOARCH
ARG GOARM
ARG BUILD_PLATFORM
FROM golang:1.17-alpine AS builder
ENV GOPROXY=https://proxy.golang.org
ENV GO111MODULE=on
ENV CGO_ENABLED=1
ENV GOOS=linux

ARG GOARCH
ENV GOARCH=${GOARCH}
ENV GOARM=${GOARM}


# Set the working directory and add application code
WORKDIR /app
ADD . .

# Copy go mod and sum files and fetch dependencies
COPY go.mod go.sum ./
RUN go mod download

# Set environment for cgo
ENV CGO_ENABLED=1

# Build
RUN CGO_ENABLED=1 GOOS=linux go build -v -o haargos-out .

# Final stage
FROM ghcr.io/hassio-addons/base/aarch64:14.3.2
WORKDIR /root/

COPY --chmod=755 run.sh ./run.sh
COPY --from=builder /app/haargos-out ./haargos

LABEL \
  io.hass.version="1.0.42" \
  io.hass.type="addon" \
  io.hass.arch="armhf|aarch64|i386|amd64"

CMD ["./run.sh"]
