name: Release Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            goarch: amd64
            platform: amd64
            compiler_link: https://musl.cc/x86_64-linux-musl-cross.tgz
            compiler_binary_name: x86_64-linux-musl-gcc
          - arch: i386
            goarch: 386
            platform: i386
            compiler_link: https://musl.cc/i486-linux-musl-cross.tgz
            compiler_binary_name: i486-linux-musl-gcc
          - arch: armv7
            goarch: arm
            platform: arm/v7
            goarm: 7
            compiler_link: https://musl.cc/armv7m-linux-musleabi-cross.tgz
            compiler_binary_name: armv7m-linux-musleabi-gcc
          - arch: armhf
            goarch: arm
            platform: armhf
            goarm: 6
            compiler_link: https://musl.cc/armv6-linux-musleabihf-cross.tgz
            compiler_binary_name: armv6-linux-musleabihf-gcc
          - arch: aarch64
            goarch: arm64
            platform: arm64
            compiler_link: https://musl.cc/aarch64-linux-musl-cross.tgz
            compiler_binary_name: aarch64-linux-musl-gcc
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker-addon/Dockerfile
          push: true
          tags: |
            haargos/${{ matrix.arch }}:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            HAARGOS_VERSION=${{ steps.get_version.outputs.VERSION }}
            GOARCH=${{ matrix.goarch }}
            BUILD_PLATFORM=${{ matrix.platform }}
            GOARM=${{ matrix.goarm }}
            FINAL_IMAGE=ghcr.io/hassio-addons/base/${{ matrix.arch }}:14.3.2
            COMPILER_LINK=${{ matrix.compiler_link }}
            COMPILER_BINARY_NAME=${{ matrix.compiler_binary_name }}
