name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # Trigger on push to the main branch. Change as needed.

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.amd64
          push: true
          tags: thaxsillion/haargos-addon:latest-amd64
          build-args: VERSION=${{ github.sha }}

  build-i386:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (i386)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.386
          push: true
          tags: thaxsillion/haargos-addon:latest-i386
          build-args: VERSION=${{ github.sha }}

