name: Release Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            dockerfile: docker-addon/Dockerfile.generic
            goarch: amd64
            platform: amd64
            dest_image: ghcr.io/hassio-addons/base/amd64:14.3.2
          - arch: i386
            dockerfile: docker-addon/Dockerfile.generic
            goarch: 386
            platform: i386
            dest_image: ghcr.io/hassio-addons/base/i386:14.3.2
          - arch: armv7
            dockerfile: docker-addon/Dockerfile.generic
            goarch: arm
            platform: arm/v7
            goarm: 7
            dest_image: ghcr.io/hassio-addons/base/armv7:14.3.2
          - arch: armhf
            dockerfile: docker-addon/Dockerfile.generic
            goarch: arm
            platform: armhf
            goarm: 6
            dest_image: ghcr.io/hassio-addons/base/armhf:14.3.2
          - arch: aarch64
            dockerfile: docker-addon/Dockerfile.generic
            goarch: arm64
            platform: arm64
            dest_image: ghcr.io/hassio-addons/base/aarch64:14.3.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: haargos/${{ matrix.arch }}:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            GOARCH=${{ matrix.goarch }}
            BUILD_PLATFORM=${{ matrix.platform }}
            GOARM=${{ matrix.goarm }}
            FINAL_IMAGE=${{ matrix.dest_image }}
